[workspace]
resolver = "2"
members = ["crates/car-thing-bin", "crates/car-thing-lib"]

[workspace.lints.clippy]
std_instead_of_core = "warn"
std_instead_of_alloc = "warn"
alloc_instead_of_core = "warn"
