[package]
name = "car-thing-bin"
version = "0.1.0"
edition = "2021"
description = "A tool to interact with Car Thing devices"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
car-thing-lib = { path = "../car-thing-lib" }

[lints]
workspace = true
