name: Build
on:
  pull_request:

jobs:
  test:
    name: Build and Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Build and test
        run: cargo test --all-features
      - name: Lint
        run: cargo clippy -- -Dwarnings
